### ISSUE TITLE
Train on more than a single image

### ISSUE THREAD

**Issue by LRpz** [softmatterlab/DeepTrack-2.0#108]
Hi, 

I was wondering if more than one image could be used when generating the training set for LodeSTAR. 

Thank you very much! 
L

**Comment by BptGrm** [comment]
I think [this](https://github.com/softmatterlab/DeepTrack-2.0/discussions/100#discussioncomment-2339348) might be what you're looking for ?

**Comment by BenjaminMidtvedt** [comment]
That's right! We recommend using a few crops for training where possible, though there are diminishing returns the more you add.

**Comment by LRpz** [comment]
> 

Yes! In that case, I would call `training_images` rather than `training_set` in 
`generator = dt.models.lodestar.LodeSTARGenerator(
    training_set,
    3, 
    (group, equivariance), 
    batch_size=8, 
    min_data_size=200, 
    max_data_size=201
)`
?

Thanks a lot!

**Comment by BenjaminMidtvedt** [comment]
An example would be

```python
training_images = [crop1, crop2, crop3, ...]
random_sampler = dt.Value(lambda: random.choice(training_images))
generator = dt.models.lodestar.LodeSTARGenerator(random_sampler, 3, ...)
```
