### ISSUE TITLE
Differences in image generation between DeepTrack 2.0 and 2.1

### ISSUE THREAD

**Issue by boupojp** [softmatterlab/DeepTrack-2.0#117]
Hi!

We have noticed some differences between DeepTrack 2.0 and 2.1 in the way they generate images through dt.Sphere and dt.Brightfield features. The dependence of z resolution on generated images is different between both versions (Currently, we are adjusting the z resolution of the simulation, by setting the resolution parameter in dt.Brightfield to a vector of length 3). This seems to originating from the upscale parameter in dt.Brightfield, which in DT 2.1 doesn't seem to be working.

You can reproduce the issue in this [colab](https://colab.research.google.com/github/boupojp/issueDT20-21/blob/main/DeepTrackIssue.ipynb) notebook. If you set the version to DT 2.0 (by setting oldversion = 1), you can see that with upscale = 4, the z resolution doesn't affect the image generation. Instead using upscale < 4, the z resolution affects the sphere image generation. Whereas, In DT 2.1 the z resolution affects the image generation with any value of upscale.

**Comment by boupojp** [comment]
Edit: 
with the last update of DeepTrack, if I set `resolution  = array_like[float, float, float] ` in `Brightfield`

``` 
import deeptrack as dt

optics = dt.Brightfield(
        wavelength=633e-9,
        NA=1,
        resolution=[pix_size * 1e-6, pix_size * 1e-6, z_pix_size * 1e-6],
        magnification=1,
        refractive_index_medium=1.33,
        upscale=4,
        pupil = dt.GaussianApodization(sigma=apod_val),
        output_region=(0, 0, image_size[0], image_size[1]),
        )
```
I obtain this error
```
[/usr/local/lib/python3.7/dist-packages/deeptrack/optics.py](https://localhost:8080/#) in _process_properties(self, propertydict)
    350         radius = NA / wavelength * resolution * magnification
    351 
--> 352         if radius > 0.5:
    353             required_upscale = np.ceil(radius * 2)
    354             warnings.warn(

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Using `resolution = float`, it works.

**Comment by giovannivolpe** [comment]
@BenjaminMidtvedt 
On the first point, I agree. The crucial part will be to introduce a fix that works.
I'd set the names zpx (and have also xpx and ypx for consistency) and z_resolution.

On the second point, I'm ok also with this. Upscale seems ok.
