### ISSUE TITLE
Conflicting behaviour with output region

### ISSUE THREAD

**Issue by HarshithBachimanchi** [softmatterlab/DeepTrack-2.0#124]
Hi!

There seems to be difference in how the `output_region` is computed in `dt.Optics` and in `dt.SampleToMasks`. 

`dt.Optics` seems to be taking `output_region` as `[x, y, x + width, y + height]` (last two values in the array are also being considered as coordinates), whereas `dt.SampleToMasks` takes it as `[x, y, width, height]`.

Any one of this would work fine (probably the second style is better), but this needs to made consistent across both.

**Comment by BenjaminMidtvedt** [comment]
Thanks! We will correct this such that both are of the style [x, y, x + width, y + height] to keep it backward compatible.

**Comment by BenjaminMidtvedt** [comment]
Closed by #127
