### ISSUE TITLE
An error occurred when using generators

### ISSUE THREAD

**Issue by JesusPinedaC** [softmatterlab/DeepTrack-2.0#16]
**System information**

I am using Google Colab with: 

- **OS Platform and Distribution**: Linux Ubuntu 18.04.3 LTS
- **Python version**: 3.6.9
- **TensorFlow version**: `` !pip list | grep tensorflow``

<p align="center">
  <img width="210" height="135" src=https://github.com/JesusPinedaC/DeepTrack-2.0/blob/master/Tutorials/Single-tracking/output/bug1.png?raw=true>
</p>

- **Keras version** : 2.3.1-tf
- **GPU model and memory**:  ``!nvidia-smi``

<p align="center">
  <img width="500" height="250" src=https://github.com/JesusPinedaC/DeepTrack-2.0/blob/master/Tutorials/Single-tracking/output/bug2.png?raw=true>
</p>

**Problem description**

I am using DeepTrack-2.0 for single-particle tracking.  To train the model, I defined a generator using the DeepTrack module `generators`, as follows,

```python
from deeptrack.generators import Generator
from deeptrack.simulation import giver

# Specify the feature of interest
getproperty = giver("position")

# Define generator
generator = Generator().generate(ImagedParticle, label_function = getproperty)
```
where `giver` is defined as:

```python
class giver:

    def __init__(self, target = "position",
                 training = False, *args):

      self.target = target
      self.training = training

    def __call__(self, image):

      for property in image.properties:

        if self.target in property:
          self.data = property[self.target]

        if self.training:
          return self.data/np.size(image, axis = 1)
        else:
          return self.data`
```
At this point, everything seems to work fine :+1:.  For example,

```python
# Display results
fig, axs = plt.subplots(1, 4, figsize=(15, 60))

for i in range(4):

  # Generate images and labels
  Image, position = next(generator)

  # plot the position of the particles as red crosses
  # on the generated image.
  axs[i].imshow(np.squeeze(Image))
  axs[i].scatter(position[:,1], position[:,0], c= "r", marker="x")
  axs[i].axis('off')

plt.show()
```
<p align="center">
  <img width="1000" height="150" src=https://github.com/JesusPinedaC/DeepTrack-2.0/blob/master/Tutorials/Single-tracking/output/Image-6.png?raw=true>
</p>

However, when training a convolutional neural network my program all the sudden gets killed without an error message  :-1::

```python
# Define generator
getproperty = giver("position", training = True)
generator = Generator().generate(ImagedParticle,
                                 label_function = getproperty,
                                 batch_size = 32)

# Train model
model.fit(generator, epochs = 100, steps_per_epoch = 10)
```
<p align="center">
 <img width="500" height="45" src=https://github.com/JesusPinedaC/DeepTrack-2.0/blob/master/Tutorials/Single-tracking/output/bug3.png?raw=true>
</p>

The runtime logs:

<p align="center">
  <img width="700" height="300" src=https://github.com/JesusPinedaC/DeepTrack-2.0/blob/master/Tutorials/Single-tracking/output/bug4.png?raw=true>
</p>

**What I have tried**

- I increased the recursion limit:

```python
# importing the sys module
import sys

# set max depth of recursion
sys.setrecursionlimit(10**6)
```
-  There is a [discussion](https://stackoverflow.com/questions/60000573/error-occurred-when-finalizing-generatordataset-iterator-cancelled-operation-w) suggesting that it is important, that `steps_per_epoch` and `batch size` correspond. I played with this without finding any improvement.

**Comment by JesusPinedaC** [comment]
Now, I tried with `sys.setrecursionlimit(10**3)` (Python's default recursion limit), and obtained the following error message:

```python
/content/DeepTrack-2.0/deeptrack/generators.py in _get(self, features)
     84             return [feature.resolve() for feature in reversed(features)]
     85         else:
---> 86             features.update()
     87             return features.resolve()

RecursionError: maximum recursion depth exceeded while calling a Python object
```
The error seems to be related to the `update()` method.

**Comment by BenjaminMidtvedt** [comment]
The only time I have run into recursion limit issues is when I have some codependence between properties. So, for example

```
f = SomeFeature(
   foo=lambda bar: "foo" + bar,
   bar=lambda foo: "bar" + foo 
)
```

DeepTrack tries to find an order to update the properties, such that all input properties are updated before updating the dependent property. Here, foo and bar depend on each other, and will thus infinitely recurse trying to find an entry-point. (I think a version in the pipeline will change how this error is presented, as to make it more obvious.)

However, struggle to imagine this is what has gone wrong in your relatively simple case.  I would suggest 

1. Set workers=0 in model.fit. DeepTrack currently not optimized for the multi-threading keras uses. I haven't found this to be an issue, but it's not unimaginable.
2. These's line-by-line profiler in python, cProfile, which might give some insight into which function starts to recurse.
