### ISSUE TITLE
error in analyzing_videos_tutorial

### ISSUE THREAD

**Issue by zidbettencourt** [softmatterlab/DeepTrack-2.0#28]
When I try to fit the model I get this error

--------------------------------------------------------------------------------------------------------------------------------

Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\DavidDuarte\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\DavidDuarte\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\davidduarte\dt\lib\site-packages\deeptrack\generators.py", line 333, in _continuous_get_training_data
    for new_image_i, new_label_i in zip(new_image, new_label):
TypeError: zip argument #2 must support iteration

----------------------------------------------------------------------------------------------------------------------------------
I'm using the latest version available of the notebook

**Comment by BenjaminMidtvedt** [comment]
You're absolutely right, I can locally reproduce the issue. Some recent update must have broken the tutorial. In all likelihood, I will have this fixed before the end of the day. Thank you for alerting us about this issue!

**Comment by zidbettencourt** [comment]
Maybe this will help, I don't know.

I tried to check what was in the "argument #2" AKA new_label, and it printed empty. So I'm assuming that either the label function defined in the notebook is wrong or the problem is in the function in generator.py
If it is the latter, I found something suspicious in the code

-------------------------------------------------------------------------------------
            if self.label_function:
                new_label = Image(self.label_function(new_image))

            if self.batch_function:
                new_image = Image(self.batch_function(new_image))
---------------------------------------------------------------------
It just seems fishy, if I’m wrong there's no need to explain why the code is correct, I just thought it would be a good place to start looking for the bug

**Comment by BenjaminMidtvedt** [comment]
The issue should now be fixed, it is at least working on my local machine. Simply pass ndim=5 to the `ContinuousGenerator` defined in cell 30! 

If the issue persists, please reopen the issue!
