### ISSUE TITLE
Mie sphere calculation bug

### ISSUE THREAD

**Issue by Midtvedt** [softmatterlab/DeepTrack-2.0#31]
There's a bug in how the field from Mie scatterers is calculated in the latest version. likely related to automatic calculation of offset_z in the initialization of a Mie scatterer. Issue arises in deeptrack version 0.7, not in 0.6.1. 

The relation between offset_z and upscale should be revised.

**Comment by BenjaminMidtvedt** [comment]
Please check if this is solved in 0.8.3
