### ISSUE TITLE
how to obtain the correct predicted position when playing an experimental video

### ISSUE THREAD

**Issue by slnnrdl** [softmatterlab/DeepTrack-2.0#38]
In your example called "Example 2. Single particle tracking" (2-single_particle_tracking.ipynb) you play some experimental videos tracked by DeepTrack. Why do you add to the predicted position the video width/2 +1 or the video height/2 +1? 

predicted_position_y = predicted_position[0,0] * video_width + video_width / 2 + 1
predicted_position_x = predicted_position[0,1] * video_height + video_height / 2 + 1

Why is 

predicted_position_y = predicted_position[0,0] * video_width 
predicted_position_x = predicted_position[0,1] * video_height 

incorrect?
In the tutorial, when you test the trained model on some newly generated images, you just multiply the predicted position by the image size.

measured_position_x = measured_positions[i, 1] * IMAGE_SIZE
measured_position_y = measured_positions[i, 0] * IMAGE_SIZE

Thank you very much for your help!
Cheers

**Comment by BenjaminMidtvedt** [comment]
Hi! This is all down to how the label is normalized. In the example, the label is set such that (-.5, -.5) is the upper left corner and (.5, .5) is the bottom right. In the tutorial, the label is set such that (0, 0) is the upper left corner, and (1, 1) is bottom right. 

Compare `px = np.array(image.get_property("position")) / IMAGE_SIZE - 0.5` and `image.get_property("position") / IMAGE_SIZE`.

In the end, the choice has little to no impact on the final accuracy, and either standard can be chosen.
