### ISSUE TITLE
is activation applied twice?

### ISSUE THREAD

**Issue by JesusPinedaC** [softmatterlab/DeepTrack-2.0#71]
Hi :wave: ! 

In layers.py, ```layers.Dense()``` and ```_single_layer_call()``` share the kwarg  ```activation``` (please see the attached code lines). 

If the user defines ```activation = "relu"```, Relu will be applied at the dense block and after the normalization step, which might be prejudicial for the networks. 

Probably, using ```layer_act``` instead of ```activation``` helps to solve the problem. In any case, the user will still be able to use ```activation``` if they want to apply the activation directly to the dense layer. 

https://github.com/softmatterlab/DeepTrack-2.0/blob/5c18d6de2a21d011aa12d6575bd25189d2aaf7d2/deeptrack/models/layers.py#L134-L157

**Comment by BenjaminMidtvedt** [comment]
Unless you also apply the activation in the definition of the model, it should not be applied twice. That is,

```py
dense_block = dt.layers.DenseBlock(activation="relu")
... # In model
layer = block(n_features)
```

Will only have the desired activation, while

```py
dense_block = dt.layers.DenseBlock(activation="relu")
... # In model
layer = block(n_features, activation="relu")
```

I think this is reasonable. However, one way to perhaps get more consistent behaviour is:

```py
def Layer(filters, **kwargs_inner): 
    activation = kwargs_inner.pop("activation", activation)
    ....
```

Which will lets the model overwrite the user-requested activation function.
