### ISSUE TITLE
scikit-image not installed through pip + tensorflow version for GPU support

### ISSUE THREAD

**Issue by BptGrm** [softmatterlab/DeepTrack-2.0#78]
Hi,

Just as a heads up, if someone ever encounters those issues during installation : 
 - I noticed that installing `deeptrack` through pip in a fresh conda environment does not seem to install `scikit-image` by default, despite it being in `requirements.txt`. Installing it independently through pip works just fine.
 - Whenever setting up an environment for GPU support, installing CUDA separately seems to break `tensorflow`, if it was installed as a dependecy of `deeptrack` beforehand. The solution that worked for me is to install `tensorflow-gpu` on a clean environment, and then install `deeptrack`.

**Comment by BenjaminMidtvedt** [comment]
Hi! Great heads up. `scikit-image` seems to have inadvertently been removed from the dependencies. This should be remedied in the next release! For the second point, I have not personally encountered this problem, but I also don't personally use conda.  However, gpu-accelerated tensorflow is often a hassle to set up correctly, so it does not surprise me that there are cases where conda fails. I will try to reproduce!
